# Generated by Django 6.0.2 on 2026-02-10 05:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='costing_sheets/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_models', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('materials', models.JSONField()),
                ('final_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_original', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('costing_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costing.costingsheet')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costing.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('old_quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('old_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('old_total', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adjusted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='costing.modelsnapshot')),
            ],
            options={
                'ordering': ['-adjusted_at'],
            },
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costing.project'),
        ),
        migrations.CreateModel(
            name='SavedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('materials', models.JSONField()),
                ('final_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_original', models.BooleanField(default=False)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('costing_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costing.costingsheet')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costing.project')),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='modelsnapshot',
            index=models.Index(fields=['project', 'model_name'], name='costing_mod_project_dced29_idx'),
        ),
        migrations.AddIndex(
            model_name='modelsnapshot',
            index=models.Index(fields=['is_original'], name='costing_mod_is_orig_1a2f46_idx'),
        ),
        migrations.AddIndex(
            model_name='savedmodel',
            index=models.Index(fields=['project', 'product_type', 'model_name'], name='costing_sav_project_e64896_idx'),
        ),
        migrations.AddIndex(
            model_name='savedmodel',
            index=models.Index(fields=['saved_at'], name='costing_sav_saved_a_2321da_idx'),
        ),
    ]
