# Generated by Django 6.0.2 on 2026-02-12 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_project_assigned_users_project_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_users',
        ),
    ]
